jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Initialize caches
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-build-external-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/loom-cache

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-build-external-

          '
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Build artifacts
      run: ./gradlew build
name: build-pull-request
on:
  repository_dispatch:
    types: trigger-ga___build-pull-request.yml
