jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Build artifacts
      run: ./gradlew build -Pbuild.release=true
    - continue-on-error: true
      name: Upload assets to GitHub
      uses: AButler/upload-release-assets@v2.0
      with:
        files: build/libs/*[0-9].jar;LICENSE
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: build-release
on:
  repository_dispatch:
    types: trigger-ga___build-release.yml
